---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-app
  namespace: default
  labels:
    app: go-app 

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: go-app
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "go-app-config"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - "go-app-secret"
      - "go-app-tls-secret"
      - "registry-secret"
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: go-app
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-app
subjects:
- kind: ServiceAccount
  name: go-app
  namespace: default
